version: "3"
services:
  ansible:
    build:
      context: .
      dockerfile: AnsibleDockerfile
    environment:
      - "ConsumerKey=${ConsumerKey}"
      - "ConsumerSecret=${ConsumerSecret}"
      - "SafaricomProd=${SafaricomProd}"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $HOME/.aws:/root/.aws
      - ./:/usr/src/app