version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - httpbin
    volumes:
      - ./:/usr/src/app

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8009:80